---
- name: ensure fpm pool log files exist
  shell: "touch {{ item }}"
  args:
    creates: "{{ item }}"
    warn: false
  loop:
    - "{{ php_fpm_errorlog }}"
    - "{{ php_fpm_slowlog }}"
  notify: restart php-fpm

- name: set log file permissions
  file:
    path: "{{ item }}"
    state: file
    owner: "{{ php_fpm_user }}"
    group: "{{ php_fpm_group }}"
    mode: '0600'
  loop:
    - "{{ php_fpm_errorlog }}"
    - "{{ php_fpm_slowlog }}"
  notify: restart php-fpm

- name: ensure logrotate is set
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/php-fpm
    owner: root
    group: root
    mode: '0644'
