---
- name: Converge
  hosts: test-multi-01
  roles:
    - ../php-fpm
  pre_tasks:
    - name: ensure sodium dependencies are installed
      dnf:
        name: "{{ item }}"
      loop:
        - https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        - make
        - libsodium
        - libsodium-devel
